-- Drop existing table if one exist
DROP TABLE IF EXISTS ACCOUNT;

-- Create Table account to store user account information
-- ACCOUNT_STATUS CAN BE 0 - UNCONFIRMED, 1 - CONFIRMED, 2 -LOCKED
-- ACCOUNT_PERMISSION CAN BE 0 - UNCONFIRMED, 1 - CONFIRMED, 2 -LOCKED
CREATE TABLE ACCOUNT
(
ACCOUND_ID VARCHAR (30) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR (30) NOT NULL,
LAST_NAME VARCHAR (30) NOT NULL,
ACCOUNT_PASSWORD VARCHAR (30) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
ACCOUNT_STATUS INTEGER NOT NULL,
ACCOUNT_PERMISSION INTEGER NOT NULL
);

-- Create a Default Admin Account
INSERT INTO ACCOUNT
(ACCOUND_ID,
FIRST_NAME,
LAST_NAME,
ACCOUNT_PASSWORD,
EMAIL,
ACCOUNT_STATUS,
ACCOUNT_PERMISSION)
VALUES
('admintest', 'admin_first', 'admin_last','admin', 'admin@test.com', 1, 0)